[package]
name = "ydbx-grpc"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.12", features = ["tls", "tls-roots", "gzip"] }
prost = "0.13"
prost-types = "0.13"

[build-dependencies]
tonic-build = "0.12"
